<?php
/**
 * @file
 * Modifications to import process.
 */

define('NAS_IMPORT_LIVE_SITE_URL', 'http://www.audubon.org/');
define('NAS_FILES_CACHE_DIR', '/var/www/cache');
define('NAS_OLD_D6_VID_HABITAT', 96);
define('NAS_OLD_D6_VID_LOLOMOTION', 101);
define('NAS_OLD_D6_VID_COLOR', 86);
define('NAS_OLD_D6_VID_CALL_TYPE', 76);
define('NAS_OLD_D6_VID_CATEGORY', 81);
define('NAS_OLD_D6_VID_SIZE', 111);
define('NAS_OLD_D6_VID_CALL_PATTERN', 71);
define('NAS_OLD_D6_VID_WING_SHAPE', 116);
define('NAS_DEFAULT_ILLUSTRATION', 'default_illustration.png');
define('NAS_DEFAULT_BACK_COVER', 'default_background_cover.jpg');

/**
 * Implements hook_ctools_plugin_api().
 */
function nas_import_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function nas_import_feeds_plugins() {
  $info = array();
  $info['NASFeedsHTTPFetcher'] = array(
    'name' => 'NAS Feeds HTTP Fetcher',
    'description' => 'Uses cache fr HTTPFetcher.',
    'help' => 'Calls will check if we already have data cached on files system.',
    'handler' => array(
      'parent' => 'FeedsHTTPFetcher',
      'class' => 'NASFeedsHTTPFetcher',
      'file' => 'NASFeedsHTTPFetcher.inc',
      'path' => drupal_get_path('module', 'nas_import'),
    ),
  );
  return $info;
}

/**
 * Implements hook_feeds_presave().
 */
function nas_import_feeds_presave(FeedsSource $source, $entity, $item) {
  if ($entity->feeds_item->id == 'birds_import') {
    nas_import_feeds_presave_birds_import($source, $entity, $item);
  }
  if ($entity->feeds_item->id == 'news_import') {
    nas_import_feeds_presave_news_import($source, $entity, $item);
  }
}

/**
 * hook_feeds_presave for birds_import importer.
 */
function nas_import_feeds_presave_birds_import(FeedsSource $source, $entity, $item) {
  // Save speices_image field data to field_bird_photo.
  if (!empty($item['field_speices_image'])) {
    nas_import_import_image($entity, $item['field_speices_image'], 'field_bird_photo');
  }

  // Save field_rangemaps field data to field_bird_rangemap.
  if (!empty($item['field_rangemaps'])) {
    nas_import_import_image($entity, $item['field_rangemaps'], 'field_bird_rangemap');
  }

  // Save field_bird_call field data to field_bird_audio.
  if (!empty($item['field_bird_call'])) {
    foreach ($item['field_bird_call'] as $key => $value) {
      if (!isset($value['fid'])) {
        continue;
      }
      $file = nas_import_add_existing_file($value['filepath'], 'audio');
      $entity->field_bird_audio[LANGUAGE_NONE][$key]['fid'] = $file->fid;

      // Additionally save description if exist to
      // separate field field_audio_description.
      if (!empty($value['data']['description'])) {
        $file_entity = file_load($file->fid);
        $file_entity->field_audio_description[LANGUAGE_NONE][0]['value'] = $value['data']['description'];
        file_save($file_entity);
      }
    }
  }
  // Save old taxonomy terms to existed terms if match.
  if (!empty($item['taxonomy'])) {

    $bird_family_terms = array();
    $bird_region_terms = array();
    $bird_call_type_terms = array();
    $bird_color_terms = array();
    $bird_category_terms = array();
    $bird_habitat2_terms = array();
    $bird_locomotion_terms = array();
    $bird_call_pattern_terms = array();
    $bird_wing_shape_terms = array();
    $bird_size_terms = array();

    // Check if there are any terms we have to save.
    foreach ($item['taxonomy'] as $key => $value) {
      if (isset($value['name'])) {
        $term = taxonomy_get_term_by_name($value['name']);
        if (!empty($term)) {
          $term = reset($term);
          if ($term->vocabulary_machine_name == 'bird_family') {
            $bird_family_terms[] = $term;
          }
          if ($term->vocabulary_machine_name == 'bird_region') {
            $bird_region_terms[] = $term;
          }
        }
        // Additionally get terms which don't exist yet.
        if ($value['vid'] == NAS_OLD_D6_VID_COLOR) {
          $bird_color_terms[] = $value['name'];
        }
        if ($value['vid'] == NAS_OLD_D6_VID_HABITAT) {
          $bird_habitat2_terms[] = $value['name'];
        }
        if ($value['vid'] == NAS_OLD_D6_VID_LOLOMOTION) {
          $bird_locomotion_terms[] = $value['name'];
        }
        if ($value['vid'] == NAS_OLD_D6_VID_CALL_TYPE) {
          $bird_call_type_terms[] = $value['name'];
        }
        if ($value['vid'] == NAS_OLD_D6_VID_CATEGORY) {
          $bird_category_terms[] = $value['name'];
        }
        if ($value['vid'] == NAS_OLD_D6_VID_SIZE) {
          $bird_size_terms[] = $value['name'];
        }
        if ($value['vid'] == NAS_OLD_D6_VID_CALL_PATTERN) {
          $bird_call_pattern_terms[] = $value['name'];
        }
        if ($value['vid'] == NAS_OLD_D6_VID_WING_SHAPE) {
          $bird_wing_shape_terms[] = $value['name'];
        }
      }
    }
    // Save terms if exist.
    if (!empty($bird_family_terms)) {
      foreach ($bird_family_terms as $key => $term) {
        $entity->field_bird_family[LANGUAGE_NONE][$key]['tid'] = $term->tid;
      }
    }
    if (!empty($bird_region_terms)) {
      foreach ($bird_region_terms as $key => $term) {
        $entity->field_bird_region[LANGUAGE_NONE][$key]['tid'] = $term->tid;
      }
    }
    // Legacy field group.
    foreach ($bird_color_terms as $key => $term) {
      $entity->field_bird_color[LANGUAGE_NONE][] = array(
        'tid' => nas_import_term_init($term, 'bird_color')
      );
    }
    foreach ($bird_call_pattern_terms as $key => $term) {
      $entity->field_bird_call_pattern[LANGUAGE_NONE][] = array(
        'tid' => nas_import_term_init($term, 'bird_call_pattern')
      );
    }
    foreach ($bird_habitat2_terms as $key => $term) {
      $entity->field_bird_habitat2[LANGUAGE_NONE][] = array(
        'tid' => nas_import_term_init($term, 'bird_habitat')
      );
    }
    foreach ($bird_locomotion_terms as $key => $term) {
      $entity->field_bird_locomotion[LANGUAGE_NONE][] = array(
        'tid' => nas_import_term_init($term, 'bird_locomotion')
      );
    }
    foreach ($bird_call_type_terms as $key => $term) {
      $entity->field_bird_call_type[LANGUAGE_NONE][] = array(
        'tid' => nas_import_term_init($term, 'bird_call_type')
      );
    }
    foreach ($bird_category_terms as $key => $term) {
      $entity->field_bird_category[LANGUAGE_NONE][] = array(
        'tid' => nas_import_term_init($term, 'bird_category')
      );
    }
    foreach ($bird_size_terms as $key => $term) {
      $entity->field_bird_size[LANGUAGE_NONE][] = array(
        'tid' => nas_import_term_init($term, 'bird_size')
      );
    }
    foreach ($bird_wing_shape_terms as $key => $term) {
      $entity->field_bird_wing_shape[LANGUAGE_NONE][] = array(
        'tid' => nas_import_term_init($term, 'bird_wing_shape')
      );
    }
  }
  // Save field_similar_species data.
  if (!empty($item['field_similar_species'])) {
    // Set old NID as first id for futher access.
    $entity->field_related_bird[LANGUAGE_NONE][0]['target_id'] = $item['nid'];
    foreach ($item['field_similar_species'] as $key => $value) {
      if (isset($value['nid'])) {
        $entity->field_related_bird[LANGUAGE_NONE][$key + 1]['target_id'] = $value['nid'];
      }
    }
  }
  // Add default images for empty fields.
  $entity->field_bird_illustration[LANGUAGE_NONE][0]['fid'] = nas_import_get_default_image(NAS_DEFAULT_ILLUSTRATION);
  $entity->field_hero_image[LANGUAGE_NONE][0]['fid'] = nas_import_get_default_image(NAS_DEFAULT_BACK_COVER);
}

/**
 * hook_feeds_presave for news_import importer.
 */
function nas_import_feeds_presave_news_import($source, $entity, $item) {
  // Save news image to d7 field_image field.
  if (!empty($item['field_image_ref'])) {
    foreach ($item['field_image_ref'] as $field_value) {
      if (!isset($field_value['nid'])) {
        continue;
      }
      $result = drupal_http_request(LOAD_NODE_JSON_OBJECT_URL . $field_value['nid']);
      $image_node = drupal_json_decode($result->data);
      $image_node = reset($image_node);
      if (!empty($image_node['field_photo'])) {
        nas_import_import_image($entity, $image_node['field_photo'], 'field_image');
      }
    }
  }
}

/**
 * Implements hook_feeds_after_save().
 */
function nas_import_feeds_after_save(FeedsSource $source, $entity, $item, $entity_id) {
  if ($entity->feeds_item->id == 'news_import') {
    return;
  }
  // Set Press Release display for imported articles.
  $panelizer_entity = array(
    'entity_type' => 'node',
    'entity_id' => $entity->nid,
    'revision_id' => $entity->nid,
    'name' => 'node:article:press_release',
    'no_blocks' => 0,
    'css_id' => '',
    'css' => '',
    'pipeline' => 'standard',
    'contexts' => array(),
    'relationships' => array(),
    'did' => 0,
    'view_mode' => 'page_manager',
    'css_class' => '',
    'title_element' => 'H2',
    'link_to_entity' => 1,
    'extra' => array(),
  );
  drupal_write_record('panelizer_entity', $panelizer_entity);
}
/**
 * Retrieve and save remote file.
 *
 * @param object $entity
 *   I.e. node.
 * @param array $d6_field_array
 *   Drupal 6 field value array.
 * @param string $d7_field_name
 *   Name of the field for drupal 7.
 */
function nas_import_import_image($entity, $d6_field_array, $d7_field_name) {
  foreach ($d6_field_array as $key => $value) {
    if (!isset($value['fid'])) {
      continue;
    }
    $file = nas_import_add_existing_file($value['filepath'], 'image');
    $entity->{$d7_field_name}[LANGUAGE_NONE][] = array('fid' => $file->fid);

    // Additionally save Alt and Title if exist.
    if (!empty($value['data']['alt']) || (!empty($value['data']['title']))) {
      $file_entity = file_load($file->fid);
      $file_entity->field_file_image_alt_text[LANGUAGE_NONE][0]['value'] = $value['data']['alt'];
      // Save Title to a new field Credit.
      $file_entity->field_file_credit[LANGUAGE_NONE][0]['value'] = $value['data']['title'];
      file_save($file_entity);
    }
  }
}

/**
 * Custom function for saving files.
 */
function nas_import_add_existing_file($remote_filepath, $type, $uid = 1, $status = FILE_STATUS_PERMANENT) {
  $cached_filepath = variable_get('nas_cached_files_folder', NAS_FILES_CACHE_DIR) . '/' . $remote_filepath;
  if (file_exists($cached_filepath)) {
    $filepath = file_unmanaged_copy($cached_filepath, NULL, FILE_EXISTS_REPLACE);
  }
  else {
    $remote_fullpath = NAS_IMPORT_LIVE_SITE_URL . str_replace('%2F', '/', rawurlencode($remote_filepath));
    $filepath = system_retrieve_file($remote_fullpath, NULL, FALSE, FILE_EXISTS_REPLACE);

    $cached_directory = drupal_dirname($cached_filepath);
    file_prepare_directory($cached_directory, FILE_CREATE_DIRECTORY);
    file_unmanaged_copy($filepath, $cached_filepath);
  }

  $files = file_load_multiple(array(), array('uri' => $filepath));
  $file = reset($files);

  if (!$file) {
    $file = (object) array(
      'filename' => basename($filepath),
      'filepath' => $filepath,
      'filemime' => file_get_mimetype($filepath),
      'filesize' => filesize($filepath),
      'uid' => $uid,
      'status' => $status,
      'timestamp' => REQUEST_TIME,
      'uri' => $filepath,
      'type' => $type,
    );
    drupal_write_record('file_managed', $file);
  }
  return $file;
}

/**
 * Fix references after all nodes have been created.
 */
function nas_import_modify_references() {
  $type = 'bird';
  $nodes = node_load_multiple(array(), array('type' => $type));
  // First step is creating mapping of old and new nids.
  $node_bird_mapped_nids = array();
  foreach ($nodes as $node) {
    $field_related_bird = field_get_items('node', $node, 'field_related_bird');
    if (!empty($field_related_bird)) {
      $old_nid_of_current_node = $field_related_bird[0]['target_id'];
      $node_bird_mapped_nids[$old_nid_of_current_node] = $node->nid;
    }
  }
  // Second step is modifying of old nids to new nids based on mapping.
  foreach ($nodes as $node) {
    $field_related_bird = field_get_items('node', $node, 'field_related_bird');
    if (empty($field_related_bird)) {
      continue;
    }
    // We dont need old nid anymore in the array, so remove it.
    array_shift($field_related_bird);
    // Lets modify old nids to new nids.
    foreach ($field_related_bird as $key => $target_id) {
      isset($node_bird_mapped_nids[$target_id['target_id']]) ? $new_nid = $node_bird_mapped_nids[$target_id['target_id']] : $new_nid = '';
      if (!empty($new_nid)) {
        $node->field_related_bird[LANGUAGE_NONE][$key]['target_id'] = $new_nid;
      }
    }
    // Remove the last item due to shifted array.
    array_pop($node->field_related_bird[LANGUAGE_NONE]);
    // Finally update the node's field.
    field_attach_update('node', $node);
  }
}

/**
 * Implements hook_menu().
 */
function nas_import_menu() {
  $items = array();
  $items['nas/import'] = array(
    'title' => 'Import content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nas_import_import_content_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Callback form for nas/import page.
 */
function nas_import_import_content_form($form, &$form_state) {
  $form['types'] = array(
    '#type' => 'checkboxes',
    '#options' => array('bird' => t('Bird')),
    '#title' => t('Content types to import'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Submit form for nas/import page.
 */
function nas_import_import_content_form_submit($form, &$form_state) {
  if ($form_state['values']['types']['bird']) {
    // Run the same import as on the installation process.
    pp_import_nodes();
  }
  return $form;
}

/**
 * Load default image by URI, or save from module's folder if not exist.
 */
function nas_import_get_default_image($filename) {
  $default_uri = drupal_get_path('module', 'nas_import') . '/images/' . $filename;
  $public_uri = 'public://' . $filename;

  $files = file_load_multiple(array(), array('uri' => $public_uri));
  $file = reset($files);

  if ($file) {
    return $file->fid;
  }
  $filepath = file_unmanaged_copy($default_uri, NULL, FILE_EXISTS_REPLACE);
  $file = (object) array(
    'filename' => basename($filepath),
    'filepath' => $filepath,
    'filemime' => file_get_mimetype($filepath),
    'filesize' => filesize($filepath),
    'uid' => 1,
    'status' => FILE_STATUS_PERMANENT,
    'timestamp' => REQUEST_TIME,
    'uri' => $filepath,
    'type' => 'image',
  );
  drupal_write_record('file_managed', $file);
  $files = file_load_multiple(array(), array('uri' => $public_uri));
  $file = reset($files);

  return $file->fid;
}

/**
 * Cached initialization for term, returns term tid if exists,
 * creates new if no.
 *
 * @param string $name
 *   Term name.
 * @param string $vname
 *   Vocabulary machine name.
 *
 * @return int
 *   Taxonomy term tid.
 */
function nas_import_term_init($name, $vname) {
  $vid = &drupal_static(__FUNCTION__ . '_vid_' . $vname);
  if (!isset($vid)) {
    $vocab = taxonomy_vocabulary_machine_name_load($vname);
    $vid = $vocab->vid;
    unset($vocab);
  }
  $term = &drupal_static(__FUNCTION__ . '_term_' . $name . $vid);
  if (isset($term)) {
    return $term;
  }
  $taxterm = taxonomy_get_term_by_name($name, $vname);
  if (!empty($taxterm)) {
    $first_term = array_shift($taxterm);
    $term = $first_term->tid;

    return $term;
  }
  $newterm = new stdClass();
  $newterm->name = $name;
  $newterm->vid = $vid;
  taxonomy_term_save($newterm);
  $term = $newterm->tid;

  return $term;
}
